/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiQaPanel: typeof import('./src/components/ai/AiQaPanel.vue')['default']
    AiSummaryPanel: typeof import('./src/components/ai/AiSummaryPanel.vue')['default']
    AppFooter: typeof import('./src/components/common/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/common/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/common/AppSidebar.vue')['default']
    DivineCommentBadge: typeof import('./src/components/post/DivineCommentBadge.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    ImageUpload: typeof import('./src/components/common/ImageUpload.vue')['default']
    LoadingSkeleton: typeof import('./src/components/common/LoadingSkeleton.vue')['default']
    LoginForm: typeof import('./src/components/user/LoginForm.vue')['default']
    MdEditor: typeof import('./src/components/markdown/MdEditor.vue')['default']
    MdViewer: typeof import('./src/components/markdown/MdViewer.vue')['default']
    NoticeBanner: typeof import('./src/components/notice/NoticeBanner.vue')['default']
    NoticeCarousel: typeof import('./src/components/notice/NoticeCarousel.vue')['default']
    NotificationBell: typeof import('./src/components/notification/NotificationBell.vue')['default']
    PostCard: typeof import('./src/components/post/PostCard.vue')['default']
    PostList: typeof import('./src/components/post/PostList.vue')['default']
    RegisterForm: typeof import('./src/components/user/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatChart: typeof import('./src/components/admin/StatChart.vue')['default']
    Toolbar: typeof import('./src/components/markdown/Toolbar.vue')['default']
    UserAvatar: typeof import('./src/components/common/UserAvatar.vue')['default']
    VisibilitySelector: typeof import('./src/components/post/VisibilitySelector.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
